### ISSUE TITLE
CraftOS-PC Crashed on me for seemingly no reason...

### ISSUE THREAD

**Issue by z256z** [MCJack123/craftos#11]
Here is the dump: 
[CraftOS-PC.exe.5600.zip](https://github.com/MCJack123/craftos/files/4938462/CraftOS-PC.exe.5600.zip)

**Comment by MCJack123** [comment]
This was probably caused by a race condition from a timer. I believe MCJack123/craftos2@b0b7a3ce9fb56133c99b97a31630146216e59cb2 should have fixed it. Also, this is the wrong repo (CraftOS-PC 2 is at https://github.com/MCJack123/craftos2), but whatever ¯\\\_(ツ)\_/¯.
